### ISSUE TITLE
GamifierServiceTest fails: Cannot create JDBC driver of class ''

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/Gamification-Framework#34]
## Steps to reproduce

- run all tests on `GamifierServiceTest` class in your IDE or run the Gradle task *test*.

## Output

```
> Task :GamificationActionService:copyMain UP-TO-DATE
> Task :GamificationActionService:compileJava UP-TO-DATE
> Task :GamificationActionService:processResources NO-SOURCE
> Task :GamificationActionService:classes UP-TO-DATE
> Task :GamificationActionService:jar UP-TO-DATE
> Task :GamificationGamifierService:copyMain UP-TO-DATE
> Task :GamificationGamifierService:compileJava UP-TO-DATE
> Task :GamificationGamifierService:processResources NO-SOURCE
> Task :GamificationGamifierService:classes UP-TO-DATE
> Task :GamificationGamifierService:copyTest UP-TO-DATE
> Task :GamificationGamifierService:compileTestJava UP-TO-DATE
> Task :GamificationGamifierService:processTestResources NO-SOURCE
> Task :GamificationGamifierService:testClasses UP-TO-DATE
> Task :GamificationGamifierService:test
checking for expired messages
waiting for 0 agents 
No library found for i5.las2peer.services.gamificationGamifierService.GamificationGamifierService@0.1! Trying default classpath. This should not happen in a productive environment!
field not found: monitor
field not found: gitHubUserMail
field not found: gitHubUser
Service i5.las2peer.services.gamificationGamifierService.GamificationGamifierService@0.1 has been started!
No library found for i5.las2peer.services.gamificationActionService.GamificationActionService@0.1! Trying default classpath. This should not happen in a productive environment!
Service i5.las2peer.services.gamificationActionService.GamificationActionService@0.1 has been started!
Test --- Get Actions
Request: GET URI: gamification/gamifier/actions/test Content:  Content-Type: text/plain accept: */* headers: 0
attempting login with id: 86109d17e62c60cf01fa1e4e968e8cdc69219d59a04587648f253d71d49a3af51eea113ac37be9501cb196126b56d24de638e0d3f3c8cf1991aab89e215a3cb9
field not found: monitor
field not found: gitHubUserMail
field not found: gitHubUser
java.sql.SQLException: Cannot create JDBC driver of class '' for connect URL 'nullnull'
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2023)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413)
	at i5.las2peer.services.gamificationActionService.database.DatabaseManager.getConnection(DatabaseManager.java:31)
	at i5.las2peer.services.gamificationActionService.GamificationActionService.getActionsRMI(GamificationActionService.java:865)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at i5.las2peer.execution.ServiceHelper.execute(ServiceHelper.java:139)
	at i5.las2peer.security.ServiceAgentImpl.invoke(ServiceAgentImpl.java:453)
	at i5.las2peer.security.ServiceAgentImpl.lambda$handle$0(ServiceAgentImpl.java:479)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2007)
	... 15 more
Service i5.las2peer.services.gamificationGamifierService.GamificationGamifierService@0.1 has been stopped!
Service i5.las2peer.services.gamificationActionService.GamificationActionService@0.1 has been stopped!
Connector-Log:
--------------


expected:<200> but was:<500>
Expected :200
Actual   :500
<Click to see difference>

java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at i5.las2peer.services.gamificationGamifierService.GamificationGamifierServiceTest.testA1_getActions(GamificationGamifierServiceTest.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)


i5.las2peer.services.gamificationGamifierService.GamificationGamifierServiceTest > testA1_getActions FAILED
    java.lang.AssertionError at GamificationGamifierServiceTest.java:132
1 test completed, 1 failed
> Task :GamificationGamifierService:test FAILED
```

**Comment by Aran30** [comment]
The .properties file of the gamifierService is not complete, the problem should be fixed once MA-aaron will is merged
